#!/usr/bin/python3
"""
A dummy python 'executable' that writes lines to a file
for the purpose of testing the exetest package.
"""

import argparse
import os

if __name__ == "__main__":

    parser = argparse.ArgumentParser()
    parser.add_argument("-N", "--num_lines", help="number of lines to write in output file", type=int, default=3)
    parser.add_argument("--squared-even-lines", help="whether to square even line numbers", action='store_true')
    parser.add_argument("--output-file", help="output file name", default="myexe_output.txt")
    parser.add_argument("--output-path", help="output file path", default=".")
    args = parser.parse_args()

    with open(os.path.join(args.output_path, args.output_file), 'w') as f:
        for i in range(1, args.num_lines + 1):
            num = i
            if args.squared_even_lines and i % 2 == 0:
                num = i * i
            f.write(f'output line {num}\n')
